exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('places').del()
  .then(function () {
    // Inserts seed entries
    return knex('places').insert([
      {place_id: 601, place_name: 'Tofino, Vancouver Island, Canada', sport_id: 1},
      {place_id: 602, place_name: 'White Beach, Okinawa, Japan', sport_id: 1},
      {place_id: 603, place_name: 'Revelstoke, Canada', sport_id: 2},
      {place_id: 604, place_name: 'Meribel, France', sport_id: 2},
      {place_id: 605, place_name: 'Alyeska, Alaska, USA', sport_id: 2},
      {place_id: 606, place_name: 'Zermatt, Switzerland', sport_id: 16},
      {place_id: 607, place_name: 'Lost Lake Trail, US, Alaska, Seward', sport_id: 3},
      {place_id: 608, place_name: 'Colorado Trail, US, Colorado, Denver', sport_id: 3},
      {place_id: 609, place_name: 'Ambergris Caye, Belize', sport_id: 4},
      {place_id: 6010, place_name: 'The Big Island, Hawaii', sport_id: 4},
      {place_id: 6011, place_name: 'Komodo Island, Indonesia', sport_id: 4},
      {place_id: 6012, place_name: 'CLIFFS OF MOHER, IRELAND', sport_id: 5},
      {place_id: 6013, place_name: 'SNAPPER ROCKS, GOLD COAST, AUSTRALIA', sport_id: 5},
      {place_id: 6014, place_name: 'Red River Gorge in Stanton, Kentucky', sport_id: 6},
      {place_id: 6015, place_name: 'Otter Cliff in Acadia National Park, Maine', sport_id: 6},
      {place_id: 6016, place_name: 'Kalymnos Island in the Dodecanese Islands, Greece', sport_id: 6},
      {place_id: 6017, place_name: 'Grand Cayman, Cayman Islands', sport_id: 7},
      {place_id: 6018, place_name: 'Nabq Bay, Egypt', sport_id: 7},
      {place_id: 6019, place_name: 'Copacabana, Rio de Janerio, Brazil', sport_id: 8},
      {place_id: 6020, place_name: 'Miami, Florida, USA', sport_id: 8},
      {place_id: 6021, place_name: 'Inca Trail, Peru', sport_id: 9},
      {place_id: 6022, place_name: 'The Torres del Paine “W” Circuit, Torres del Paine National Park, Patagonia, Chile', sport_id: 9},
      {place_id: 6023, place_name: 'Kilimanjaro, Tanzania, Africa', sport_id: 9},
      {place_id: 6024, place_name: 'Cape Kri - Raja Ampat, Indonesia', sport_id: 10},
      {place_id: 6025, place_name: 'Barracuda Point - Sipadan Island', sport_id: 10},
      {place_id: 6026, place_name: 'Thistlegorm - Egyptian Red Sea', sport_id: 10},
      {place_id: 6027, place_name: 'MILFORD SOUND, NEW ZEALAND', sport_id: 11},
      {place_id: 6028, place_name: 'VANCOUVER ISLAND, CANADA', sport_id: 11},
      {place_id: 6029, place_name: 'TORRES DEL PAINE NATIONAL PARK, CHILE', sport_id: 11},
      {place_id: 6030, place_name: 'Bazaruto Archipelago, Mozambique', sport_id: 12},
      {place_id: 6031, place_name: 'Wengen, Canton of Bern, Switzerland', sport_id: 12},
      {place_id: 6032, place_name: 'Castelluccio, Umbria, Italy', sport_id: 12},
      {place_id: 6033, place_name: 'Julian Alps, Tolmin and Bohinj Regions, Slovenia', sport_id: 12},
      {place_id: 6034, place_name: 'Mount Everest, Nepal', sport_id: 13},
      {place_id: 6035, place_name: 'Livingstone, Zambia', sport_id: 13},
      {place_id: 6036, place_name: 'Queenstown, New Zealand', sport_id: 13},
      {place_id: 6037, place_name: 'Boracay, Philippines', sport_id: 15},
      {place_id: 6038, place_name: 'Fuerteventura, Canary Islands, Spain', sport_id: 15},
      {place_id: 6039, place_name: 'Langebaan, South Africa', sport_id: 15},
      {place_id: 6040, place_name: 'Whistler/Blackcomb , Canada', sport_id: 16},
      {place_id: 6041, place_name: 'St Anton , Austria', sport_id: 16},
      {place_id: 6042, place_name: 'GR20, France', sport_id: 17},
      {place_id: 6043, place_name: 'Pays Dogon, Mali', sport_id: 17},
      {place_id: 6044, place_name: 'Everest Base Camp, Nepal', sport_id: 17},
      {place_id: 6045, place_name: 'Valdez-Cordova, Alaska', sport_id: 18},
      {place_id: 6046, place_name: 'Yosemite National Park, California', sport_id: 18},
      {place_id: 6047, place_name: 'Mount Everest, Nepal', sport_id: 19},
      {place_id: 6048, place_name: 'Grand Canyon, USA', sport_id: 19},
      {place_id: 6049, place_name: 'Kartchner Caverns, Arizona, USA', sport_id: 20},
      {place_id: 6050, place_name: 'Harrison’s Cave - Allen View, Barbados', sport_id: 20},
      {place_id: 6051, place_name: 'CENOTE ANGELITA - TULUM, MEXICO', sport_id: 21},
      {place_id: 6052, place_name: 'EMERGENCE DU RUSSEL - DORDOGNE REGION, FRANCE', sport_id: 21},
      {place_id: 6053, place_name: 'ORDA CAVE - PERM REGION, RUSSIA', sport_id: 21},
      {place_id: 6054, place_name: 'Agawa Canyon, Canada', sport_id: 22},
      {place_id: 6055, place_name: 'Zion National Park, Utah, USA', sport_id: 22},
      {place_id: 6056, place_name: 'Blue Mountains, Australia', sport_id: 22},
      {place_id: 6057, place_name: 'The Great Ocean Road, Victoria, Australia', sport_id: 23},
      {place_id: 6058, place_name: 'The Karakoram Highway, China-Pakistan', sport_id: 23},
      {place_id: 6059, place_name: 'Cycle Route 10, Amsterdam, Holland', sport_id: 23},
      {place_id: 6060, place_name: 'Pinnacle Ridge in the Lake District, Great Britain', sport_id: 24},
      {place_id: 6061, place_name: 'Bilberry Terrace in Snowdonia, Great Britain', sport_id: 24},
      {place_id: 6062, place_name: 'Colorado River, Grand Canyon, USA', sport_id: 25},
      {place_id: 6063, place_name: 'Zambezi River, Zimbabwe', sport_id: 25},
      {place_id: 6064, place_name: 'Futaleufu River, Chile', sport_id: 25},
      {place_id: 6065, place_name: 'Valle de Bravo, Mexico', sport_id: 26},
      {place_id: 6066, place_name: 'Masai Mara, Kenya', sport_id: 26},
      {place_id: 6067, place_name: 'Loire Valley, France', sport_id: 26},
      {place_id: 6068, place_name: 'Interlaken District, Swizerland', sport_id: 27},
      {place_id: 6069, place_name: 'Magaliesburg, Johannesburg, South Africa', sport_id: 27},
      {place_id: 6070, place_name: 'Queenstown, New Zealand', sport_id: 27}
    ]);
  });
};
